name: HyperMashmau CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependecies
        run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: Run Tests
        run: npm run test:coverage
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info # optional
          fail_ci_if_error: true
          verbose: true
